# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-02 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_projeto', models.CharField(max_length=400)),
                ('nome_doador', models.CharField(max_length=300)),
                ('cgccpf', models.CharField(max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('data_recibo', models.DateField(null=True)),
                ('PRONAC', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Interessado',
            fields=[
                ('cgccpf', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=300)),
                ('responsavel', models.CharField(max_length=150, null=True)),
                ('UF', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=100)),
                ('tipo_pessoa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('PRONAC', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=100)),
                ('segmento', models.CharField(max_length=100)),
                ('cgccpf', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=400)),
                ('proponente', models.CharField(max_length=200)),
                ('mecanismo', models.CharField(max_length=100)),
                ('enquadramento', models.CharField(max_length=100)),
                ('UF', models.CharField(max_length=2)),
                ('municipio', models.CharField(max_length=100)),
                ('data_inicio', models.DateField(null=True)),
                ('ano_projeto', models.CharField(max_length=2)),
                ('data_termino', models.DateField(null=True)),
                ('valor_projeto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('outras_fontes', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('valor_captado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_proposta', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('valor_aprovado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('etapa', models.TextField(null=True)),
                ('providencia', models.TextField(null=True)),
                ('objetivos', models.TextField(null=True)),
                ('ficha_tecnica', models.TextField(null=True)),
                ('acessibilidade', models.TextField(null=True)),
                ('estrategia_execucao', models.TextField(null=True)),
                ('justificativa', models.TextField(null=True)),
                ('resumo', models.TextField(null=True)),
                ('sinopse', models.TextField(null=True)),
                ('impacto_ambiental', models.TextField(null=True)),
                ('democratizacao', models.TextField(null=True)),
                ('especificacao_tecnica', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Incentivador',
            fields=[
                ('interessado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='busca_rouanet.Interessado')),
                ('total_doado', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
            bases=('busca_rouanet.interessado',),
        ),
        migrations.CreateModel(
            name='Proponente',
            fields=[
                ('interessado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='busca_rouanet.Interessado')),
                ('quantidade_projetos', models.IntegerField()),
            ],
            bases=('busca_rouanet.interessado',),
        ),
        migrations.AddField(
            model_name='doacao',
            name='projeto_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca_rouanet.Projeto'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='proponente_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca_rouanet.Proponente'),
        ),
        migrations.AddField(
            model_name='doacao',
            name='incentivador_related',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busca_rouanet.Incentivador'),
        ),
    ]
