# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca_rouanet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='incentivadores',
            field=models.ManyToManyField(blank=True, null=True, to='busca_rouanet.Incentivador'),
        ),
    ]
