# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca_rouanet', '0002_projeto_incentivadores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='incentivadores',
        ),
        migrations.AddField(
            model_name='incentivador',
            name='projetos',
            field=models.ManyToManyField(blank=True, null=True, to='busca_rouanet.Projeto'),
        ),
    ]
