# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busca_rouanet', '0003_auto_20160615_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incentivador',
            name='projetos',
            field=models.ManyToManyField(blank=True, to='busca_rouanet.Projeto'),
        ),
    ]
